export enum CodeEvent {
    GENERATED_CODE = "GENERATED_CODE",
    ATTEMPTED_CODE = "ATTEMPTED_CODE",
    CODE_IS_NOT_VALID = "CODE_IS_NOT_VALID",
    USED_CODE = "USED_CODE",
    REMOVED_CODE = "REMOVED_CODE",
}
