import {assert} from 'chai'
import efgsDiagnosisKeysFactory from "../../../../src/functions/efgs/efgsDiagnosisKeysFactory";

describe('efgsDiagnosisKeysFactory', function () {
    it('should create efgs object', function () {

        const gensJson = "{\"data\":{\"verificationPayload\":\"eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJjb2RlIjoiMTRSSU9NIiwiaWF0IjoxNTk5Njc1OTk2LCJleHAiOjE1OTk2Nzc3OTYsImp0aSI6IjIwY2ZkMmIyLTAzNjctNGM2My1hYzZmLTE0ZjE2NzhlYWVhMyJ9.u3vfYhP9TxmJqfhvOKw1dcjApT6uLPiESMlBUclml-urNOwgKnuoBCJ0OmIK92qr4baX5-zo-9Wp_PMwKRfOXA\",\"temporaryExposureKeys\":[{\"rollingPeriod\":144,\"key\":\"w5Ki0OSYtUOadVJUdZcuUQ==\",\"rollingStartNumber\":2665872,\"transmissionRisk\":8},{\"rollingPeriod\":144,\"key\":\"vsv3YRig39qD1XqIjITbNw==\",\"rollingStartNumber\":2665728,\"transmissionRisk\":8},{\"rollingPeriod\":144,\"key\":\"WN20so3acEybGaLLps2smA==\",\"rollingStartNumber\":2665584,\"transmissionRisk\":8},{\"rollingPeriod\":144,\"key\":\"5MI\\/219zoJdPqaXQDR0YTQ==\",\"rollingStartNumber\":2665440,\"transmissionRisk\":8},{\"rollingPeriod\":144,\"key\":\"ESartjbxqW0z1qfZ3pwW2Q==\",\"rollingStartNumber\":2665296,\"transmissionRisk\":8},{\"rollingPeriod\":144,\"key\":\"qrcyBtITrUeDxrS7PoiMyg==\",\"rollingStartNumber\":2665008,\"transmissionRisk\":8},{\"rollingPeriod\":144,\"key\":\"4LfY+qZXImQj3uDVwzmAgw==\",\"rollingStartNumber\":2664864,\"transmissionRisk\":8},{\"rollingPeriod\":144,\"key\":\"7OhqYScWUGTKQ3AtUOu3XQ==\",\"rollingStartNumber\":2664720,\"transmissionRisk\":8},{\"rollingPeriod\":144,\"key\":\"SL0LBs+rxN+ho3B0Vb+hkg==\",\"rollingStartNumber\":2664144,\"transmissionRisk\":8}],\"regions\":[\"DE\"],\"appPackageName\":\"pl.gov.mc.protegosafe-staging\",\"platform\":\"ios\"}}";
        const gensItem = JSON.parse(gensJson);

        const exceptedEfgsJson = "{\"keys\":[{\"keyData\":\"w5Ki0OSYtUOadVJUdZcuUQ==\",\"rollingStartIntervalNumber\":2665872,\"rollingPeriod\":144,\"transmissionRiskLevel\":8,\"visitedCountries\":[\"DE\"],\"origin\":\"PL\",\"reportType\":2,\"days_since_onset_of_symptoms\":42},{\"keyData\":\"vsv3YRig39qD1XqIjITbNw==\",\"rollingStartIntervalNumber\":2665728,\"rollingPeriod\":144,\"transmissionRiskLevel\":8,\"visitedCountries\":[\"DE\"],\"origin\":\"PL\",\"reportType\":2,\"days_since_onset_of_symptoms\":42},{\"keyData\":\"WN20so3acEybGaLLps2smA==\",\"rollingStartIntervalNumber\":2665584,\"rollingPeriod\":144,\"transmissionRiskLevel\":8,\"visitedCountries\":[\"DE\"],\"origin\":\"PL\",\"reportType\":2,\"days_since_onset_of_symptoms\":42},{\"keyData\":\"5MI/219zoJdPqaXQDR0YTQ==\",\"rollingStartIntervalNumber\":2665440,\"rollingPeriod\":144,\"transmissionRiskLevel\":8,\"visitedCountries\":[\"DE\"],\"origin\":\"PL\",\"reportType\":2,\"days_since_onset_of_symptoms\":42},{\"keyData\":\"ESartjbxqW0z1qfZ3pwW2Q==\",\"rollingStartIntervalNumber\":2665296,\"rollingPeriod\":144,\"transmissionRiskLevel\":8,\"visitedCountries\":[\"DE\"],\"origin\":\"PL\",\"reportType\":2,\"days_since_onset_of_symptoms\":42},{\"keyData\":\"qrcyBtITrUeDxrS7PoiMyg==\",\"rollingStartIntervalNumber\":2665008,\"rollingPeriod\":144,\"transmissionRiskLevel\":8,\"visitedCountries\":[\"DE\"],\"origin\":\"PL\",\"reportType\":2,\"days_since_onset_of_symptoms\":42},{\"keyData\":\"4LfY+qZXImQj3uDVwzmAgw==\",\"rollingStartIntervalNumber\":2664864,\"rollingPeriod\":144,\"transmissionRiskLevel\":8,\"visitedCountries\":[\"DE\"],\"origin\":\"PL\",\"reportType\":2,\"days_since_onset_of_symptoms\":42},{\"keyData\":\"7OhqYScWUGTKQ3AtUOu3XQ==\",\"rollingStartIntervalNumber\":2664720,\"rollingPeriod\":144,\"transmissionRiskLevel\":8,\"visitedCountries\":[\"DE\"],\"origin\":\"PL\",\"reportType\":2,\"days_since_onset_of_symptoms\":42},{\"keyData\":\"SL0LBs+rxN+ho3B0Vb+hkg==\",\"rollingStartIntervalNumber\":2664144,\"rollingPeriod\":144,\"transmissionRiskLevel\":8,\"visitedCountries\":[\"DE\"],\"origin\":\"PL\",\"reportType\":2,\"days_since_onset_of_symptoms\":42}]}";

        const efgsItem = efgsDiagnosisKeysFactory(gensItem);
        assert.deepEqual(efgsItem, JSON.parse(exceptedEfgsJson))
    });
});
